server:
  port: 8080
  tomcat:
    threads:
      max: 20
      min-spare: 2
    max-connections: 100

spring:
  datasource:
    url: jdbc:postgresql://zephyr.proxy.rlwy.net:42378/railway?sslmode=require
    username: postgres
    password: YRSOJGiOGURXjtoPTZDHVstTgLtkttbJ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

# JWT Configurations
app:
  jwt:
    secret: ${JWT_SECRET:9a4f2c8d3b7a1e5c8f9d0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours
