server:
  port: 8080
  tomcat:
    threads:
      max: 20
      min-spare: 2
    max-connections: 100

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false

# App Configurations
app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: ${JWT_EXPIRATION_MS:} # 60 days
  resend:
    api-key: ${RESEND_API_KEY:}
    from: ${RESEND_FROM:}
    admin-email: tranvanhuy064206@gmail.com
  google:
    client-id: ${GOOGLE_CLIENT_ID:}

